### ISSUE TITLE
Import existing SQL from previous directus instance

### ISSUE THREAD

**Issue by MrSunshyne** [kadumedim/directus-starter#20]
Is it possible to have a `.sql` file somewhere in the repository, which, if it exists, would be automatically imported when this template is provisioned on railway?

## Use case
A lot of people will have to migrate from the Directus Cloud - Community instances, which have been discontinued. For now the directus team is providing admins with a db dump of their instance, which in theory should restore the full application with its data.

**Comment by kadumedim** [comment]
You can't import .sql files on a railway DB directly as far as I know and I don't know if Directus does that, haven't used it in a long time.
You can fork this repo and give it a try!
