### ISSUE TITLE
Image access after redeploy

### ISSUE THREAD

**Issue by florian-vigneron** [kadumedim/directus-starter#34]
Hello, I have a problem when I redeploy my directus railway image :

<img width="1202" alt="image" src="https://github.com/kadumedim/directus-starter/assets/12138587/2de47d65-0d18-497d-a8cb-e2a33c8f61fd">

I always have to re-upload my images. Is there not a problem of access rights on the images?

Thanks

**Comment by kadumedim** [comment]
Service storage in railway is non-persistent, A.K.A everytime you redeploy it will erase your storage.
What u can do to prevent this is using an S3 (or other option) Adapter, alternatively, Railway now includes a persistent volume storage (cost is separated) which u can use too.
