### ISSUE TITLE
Introspection issue using GraphQL

### ISSUE THREAD

**Issue by djmtype** [kadumedim/directus-starter#4]
Maybe this is a me-problem, but I can't get this Railway starter to work properly when trying to see my graphql endpoint in Altair or GraphiQL. Mind you, I have installed Directus locally and on other remote servers and have had no issues accessing the graphql schema in any graphql client. 
I can  successfully return the data from my Directus graphql endpoint using the fetch API. However, Altair and GraphiQL keep telling me there's an introspection error. 
This is also my first time using Railway, so I don't know if this needs to be addressed with them. I have already posted my question on their Discord Channel as well as Directus Discord, but it seems no one has run into this problem.

Here is the error I get in Altair. GraphiQL is similar.
```
{
  "errors": [
    {
      "message": "GraphQL schema validation error.",
      "extensions": {
        "code": "INVALID_PAYLOAD",
        "graphqlErrors": [
          {
            "message": "Syntax Error: Unexpected <EOF>.",
            "locations": [
              {
                "line": 5,
                "column": 1
              }
            ]
          }
        ]
      }
    }
  ]
}
```

**Comment by kadumedim** [comment]
Oh man... i don't think i can help you since i don't use GraphQL or Altair. You better post it on the help channel on railway's discord (https://discord.gg/railway) or even on directus discord server

**Comment by djmtype** [comment]
Thanks @kadumedim  I have been asking on both channels.
