### ISSUE TITLE
Railway fails to build when KEY includes hyphens

### ISSUE THREAD

**Issue by djmtype** [kadumedim/directus-starter#5]
I tried twice and both times Railway failed to build my Directus project using this template when the KEY value was set with hyphens. If you use a UUID generator it normally contains hyphens.

I don't know if it's coincidence, but on the 3rd attempt I removed all hyphens and my project built. I tried this again on another try just to make sure.

Can you please verify when adding something like 1651159c-4a53-11ed-b878-0242ac120002 as the KEY it will also fail? As it may be by coincidence.

**Comment by kadumedim** [comment]
Yep, also fails for me. Try using a key that doesnt contains hyphens, this bug is on directus so you can also report it on their discord.
